title: Angular Seed
description: High-quality, modular starter project for Angular 2 (and beyond) with statically typed build and AoT
google_analytics: UA-18060688-18
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
